apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kaushaljethva07-site-tls
spec:
  secretName: kaushaljethva07-site
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: kaushaljethva07.site
  dnsNames:
    - kaushaljethva07.site
    - www.kaushaljethva07.site
